FROM ghcr.io/ggml-org/llama.cpp:server-cuda

ENV LLAMA_ARG_HF_REPO=PkmX/orpheus-3b-0.1-ft-Q8_0-GGUF
ENV LLAMA_ARG_HF_FILE=orpheus-3b-0.1-ft-q8_0.gguf
ENV LLAMA_ARG_CTX_SIZE=0
ENV LLAMA_ARG_N_GPU_LAYERS=-1
